name: kernel-x
version: 4.x
summary: Linux kernel snap for Ubutu Core
description: |
  Linux kernel snap for Ubutu Core

  1) Secure boot must off
  2) Reworked kernel gets no online updates
grade: stable
confinement: strict
type: kernel
parts:
  kernel:
    plugin: make
    source: ../ubuntu-xenial/
    makefile: Makefile.xenial
    prepare: |
      cp $SNAPCRAFT_STAGE/../Makefile.xenial $SNAPCRAFT_PART_INSTALL/../src
      cp $SNAPCRAFT_STAGE/../Makefile.xenial $SNAPCRAFT_PART_INSTALL/../build
      cd $SNAPCRAFT_STAGE/build
      fakeroot debian/rules clean
      fakeroot debian/rules binary-generic
    make-parameters:
      - LOCAL_KERNEL_PATH=$SNAPCRAFT_PART_INSTALL/../
      - RELEASE=xenial
    build-packages:
      - debootstrap
      - lsb-release
  marvell:
    source: mrvl
    after: [kernel]
    plugin: dump
    organize:
        pcie8897_uapsta.bin: lib/firmware/mrvl/pcie8897_uapsta.bin

